DROP TABLE IF EXISTS ACCOUNT_DETAILS;
DROP TABLE IF EXISTS Transaction;

CREATE TABLE ACCOUNT_DETAILS (
    ACCOUNT_NUMBER INTEGER,
    BALANCE DECIMAL(7,2),
    CURRENCY VARCHAR(10)
);

CREATE TABLE Transaction(
	TRANSACTIONID INTEGER,
	ACCOUNTID INTEGER,
    AMOUNT DECIMAL(7,2),
    TRANSACTION_TIME Timestamp,
    TRANSACTION_DESC VARCHAR(255),
    TRANSACTION_TYPE VARCHAR(10),
    CURRENCY VARCHAR(10)
);

